Apply plugin-template #3

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,10 +43,45 @@ jobs:
         run: |
           .github/workflows/scripts/check_commit.sh
 
+  check-changes:
+    runs-on: ubuntu-latest
+    outputs:
+      run_tests: ${{ steps.check.outputs.run_tests }}
+    steps:
+      - uses: "actions/checkout@v4"
+        with:
+          fetch-depth: 0
+          path: "pulp_rpm"
+
+      - uses: "actions/setup-python@v5"
+        with:
+          python-version: "3.12"
+
+      - name: "Install python dependencies"
+        run: |
+          echo ::group::PYDEPS
+          pip install gitpython
+          echo ::endgroup::
+
+      - name: Analyze changed files
+        shell: bash
+        id: check
+        run: |
+          set +e
+          python3 .ci/scripts/skip_tests.py . origin/main
+          exit_code=$?
+          if [ $exit_code -ne 0 ] && [ $exit_code -ne 1 ]; then
+            echo "Error: skip_tests.py returned unexpected exit code $exit_code"
+            exit $exit_code
+          fi
+          echo "run_tests=$exit_code" >> $GITHUB_OUTPUT
+
   docs:
     uses: "./.github/workflows/docs.yml"
 
   lint:
+    needs: check-changes
+    if: needs.check-changes.outputs.run_tests == '1'
     uses: "./.github/workflows/lint.yml"
 
   build:
@@ -84,11 +119,28 @@ jobs:
     # This is a dummy dependent task to have a single entry for the branch protection rules.
     runs-on: "ubuntu-latest"
     needs:
+      - "check-changes"
       - "check-commits"
       - "lint"
       - "test"
       - "docs"
-    if: "always()"
+    if: needs.check-changes.outputs.run_tests == '1'
+    steps:
+      - name: "Collect needed jobs results"
+        working-directory: "."
+        run: |
+          echo '${{toJson(needs)}}' | jq -r 'to_entries[]|select(.value.result!="success")|.key + ": " + .value.result'
+          echo '${{toJson(needs)}}' | jq -e 'to_entries|map(select(.value.result!="success"))|length == 0'
+          echo "CI says: Looks good!"
+
+  ready-to-ship-docs-only:
+    # Readiness check doc-only changes
+    runs-on: "ubuntu-latest"
+    needs:
+      - "check-changes"
+      - "check-commits"
+      - "docs"
+    if: needs.check-changes.outputs.run_tests == '0'
     steps:
       - name: "Collect needed jobs results"
         working-directory: "."
